/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_clarenceho_jnimap_JniMap */

#ifndef _Included_net_clarenceho_jnimap_JniMap
#define _Included_net_clarenceho_jnimap_JniMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_clarenceho_jnimap_JniMap
 * Method:    process
 * Signature: ()V
 */
JNIEXPORT jobject JNICALL Java_net_clarenceho_jnimap_JniMap_process
  (JNIEnv *, jobject, jint, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
